# Generated by Django 4.2.2 on 2023-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='tg_bot.user', verbose_name='Участники мероприятия'),
        ),
    ]
