# Generated by Django 4.2.2 on 2023-06-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0002_alter_event_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='members',
            field=models.ManyToManyField(related_name='events', to='tg_bot.user', verbose_name='Участники мероприятия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Признак администратора'),
        ),
    ]
