# Generated by Django 4.2.2 on 2023-06-22 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0003_alter_event_members_alter_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='do_not_notify',
            field=models.BooleanField(default=False, verbose_name='Не предлагать продление'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='speaker_speeches', to='tg_bot.user', verbose_name='Докладчик'),
        ),
    ]
