# Generated by Django 4.2.2 on 2023-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0005_remove_user_speciality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='members',
        ),
        migrations.AddField(
            model_name='event',
            name='meeters',
            field=models.ManyToManyField(related_name='events', to='tg_bot.user', verbose_name='Заполнили анкету на мероприятии'),
        ),
    ]
