# Generated by Django 4.2.2 on 2023-06-25 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0006_remove_event_members_event_meeters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='image',
        ),
    ]
